### ISSUE TITLE
[Enhancement] HL Compatibility

### ISSUE THREAD

**Issue by SomeGuyWhoLovesCoding** [jeremyfa/linc_soloud#1]
It appears that some guy has said streaming works fine. There sure is one thing that's missing, which is HashLink support.
My FNF project is cross platform ignoring web targets, and I'm also curious if it has mac and linux support too.

**Comment by SomeGuyWhoLovesCoding** [comment]
Even though this is a linc library, I also need hashlink support, which is definitely a neat feature.

**Comment by SomeGuyWhoLovesCoding** [comment]
Also there are no cpp files so this is perfect for HashLink compatibility.

**Comment by SomeGuyWhoLovesCoding** [comment]
There are extern classes that use cpp though.

**Comment by jeremyfa** [comment]
I have no plans to make this work with HL because I don’t use HL. You can always try to adapt the work for HL bindings yourself though.

**Comment by SomeGuyWhoLovesCoding** [comment]
> I have no plans to make this work with HL because I don’t use HL. You can always try to adapt the work for HL bindings yourself though.

Ok
